aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    openshift.io/description: A user that has pods/exec and pods/portforward within the project
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: null
  name: strimzi-pod-exec-and-portforward
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  - pods/portforward
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
